### ISSUE TITLE
`unable to connect any locator of scouted peer` zenoh-plugin-dds 

### ISSUE THREAD

**Issue by akila-ganlath-tm** [eclipse-zenoh/zenoh-python#55]
I am trying to use the Zenoh Python API with pycdr as in the [demo](https://github.com/eclipse-zenoh/zenoh-demos/tree/master/ROS2/zenoh-python-teleop) to interface with cycloneDDS via zenoh-plugin-dds. The Python api was installed via pip: `eclipse-zenoh-nightly` I noticed that the python API examples don't seem to be compatible with the `master` or `latest` zenoh-plugin-dds docker image:
`Unable to connect any locator of scouted peer D6B17F40D8234F80AE42D205FCB23673 : [Locator { address: Tcp(SocketAddr(192.168.0.62:33681)), metadata: None }, Locator { address: Tcp(SocketAddr(172.17.0.1:33681)), metadata: None }]`
I have tried the master and apis-merge branches of the Python API but no luck. Should I build the Python API from source instead of using the PyPi binary?

**Comment by JEnoch** [comment]
The `latest` tag of `zenoh-plugin-dds` docker image corresponds to the latest release (i.e. 0.5.0-beta.9). It won't be compatible with the current `eclipse-zenoh-nightly` for Python, as we made some changes in the protocol since this release.

However the `master` tag (or `nightly` tag which refers the same image) should be compatible. Please try to pull it again, and check that you well have the latest DIGEST installed, as listed here: https://hub.docker.com/r/eclipse/zenoh-bridge-dds/tags

**Comment by akila-ganlath-tm** [comment]
Thanks @JEnoch!
