### ISSUE TITLE
API alignment

### ISSUE THREAD

**Issue by Mallets** [eclipse-zenoh/zenoh-python#57]
Semantic and naming should be aligned across all zenoh API bindings: Rust, C, Python, and more to come.

**Comment by Mallets** [comment]
Tracking upstream roadmap issue https://github.com/eclipse-zenoh/roadmap/issues/3

**Comment by JEnoch** [comment]
TODO:

- [ ] Remove queryable kind (same as eclipse-zenoh/zenoh#236)
- [ ] Document `Session.undeclare_publication()` and `AsyncSession/undeclare_publication()`.
- [ ] Add `Session.id` and `AsyncSession.id`
- [ ] Expose in `KeyExpr` the `scope` and `suffix` attributes
- [ ] Make `Sample.key_expr` a `KeyExpr` instead of a `str`
- [ ] Add `Session.key_expr_to_expr(KeyExpr) -> str`
- [ ] Rewrite doc of `Query`'s functions
- [ ] `Sample` : set `source_info` and `timestamp` as kwargs of constructor 
- [ ] Remove `SampleKind.DEFAULT`

**Comment by Mallets** [comment]
Update: the look-and-feel of the new API is captured in https://github.com/eclipse-zenoh/roadmap/discussions/23

**Comment by Mallets** [comment]
Merged into master.
